_BASE_: "../Base-RCNN-FPN.yaml"

MODEL:
  MASK_ON: False
  WEIGHTS: "output/model_0244999.pth"  # 重みファイルのパスを指定
  PIXEL_STD: [57.375, 57.120, 58.395]
  ROI_HEADS:
    NUM_CLASSES: 2
  RESNETS:
    STRIDE_IN_1X1: False
    NUM_GROUPS: 32
    WIDTH_PER_GROUP: 8
    DEPTH: 101

DATASETS:
  TEST: ("custom_dataset_val",)

TEST:
  DETECTIONS_PER_IMAGE: 100  # 1つの画像に対して描画するバウンディングボックスの最大数
